using System.Security;
using System.Text;
using System.Text.RegularExpressions;

namespace ExcelGenerator;

/// <summary>
/// 공용 상수 시트(<c>Constants.xlsx</c>의 <c>ConstantsTable</c>)의 <b>행 하나마다 속성 하나</b>를 가진
/// <c>GameData.Constants</c> 정적 클래스를 만든다. 서버·클라가 <c>Constants.StorageCapacity</c>로 같은 값을 읽는다.
///
/// 행을 지우면 그 값을 쓰던 코드가 <b>컴파일에서</b> 깨진다 — 문자열 키로 찾을 때처럼 런타임까지 숨지 않는다.
/// 값은 전부 <c>long</c>이고, 소수는 천분율 정수로 적는다(이름 끝 <c>Permille</c>).
/// </summary>
internal static class ConstantsGenerator
{
    public const string TableName = "ConstantsTable";
    public const string FileName  = "Constants.cs";

    private const string NameColumn        = "Name";
    private const string ValueColumn       = "Value";
    private const string DescriptionColumn = "Description";

    // 속성 이름이 되므로 C# 식별자여야 하고, 다른 코드와 같은 PascalCase로 강제한다.
    private static readonly Regex IdentifierPattern = new("^[A-Z][A-Za-z0-9]*$", RegexOptions.Compiled);

    private const string Header =
        "// <auto-generated>\n" +
        "// 이 파일은 ExcelGenerator가 Constants.xlsx(ConstantsTable)의 행으로부터 생성했습니다. 직접 수정 금지.\n" +
        "// </auto-generated>\n\n";

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    /// <summary>
    /// 상수 시트가 있으면 <c>Constants.cs</c>를 만들고, 없으면 옛 파일을 지운다(시트를 지웠는데 클래스가 남으면 빈 테이블을 읽다 터진다).
    /// 시트 모양이 규약과 다르면 파이프라인을 멈춘다.
    /// </summary>
    public static void Generate(IReadOnlyList<ExcelGenerator.TableData> tables, string gameDataDir)
    {
        var path  = Path.Combine(gameDataDir, FileName);
        var table = tables.FirstOrDefault(t => t.Name == TableName);
        if (table is null)
        {
            if (File.Exists(path))
            {
                File.Delete(path);
            }
            return;
        }

        var constants = Read(table);
        File.WriteAllText(path, Header + Build(constants), Utf8NoBom);
        Console.WriteLine($"[코드 생성] Constants: 상수 {constants.Count}개 → GameData/{FileName}");
    }

    private sealed record Constant(string Name, string Description);

    private static List<Constant> Read(ExcelGenerator.TableData table)
    {
        var name        = ColumnIndex(table, NameColumn, ExcelGenerator.ColumnInfo.RecordType.String);
        var value       = ColumnIndex(table, ValueColumn, ExcelGenerator.ColumnInfo.RecordType.Long);
        var description = ColumnIndex(table, DescriptionColumn, ExcelGenerator.ColumnInfo.RecordType.String);

        if (name != 0)
        {
            throw new InvalidDataException($"{TableName}: 첫 컬럼은 {NameColumn}이어야 한다 — 이름이 곧 키다.");
        }

        var seen   = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<Constant>();
        foreach (var row in table.Rows)
        {
            var n = Cell(row, name).Trim();
            if (!IdentifierPattern.IsMatch(n))
            {
                throw new InvalidDataException($"{TableName}: 이름 '{n}'은 PascalCase 영문 식별자여야 한다(속성 이름이 된다).");
            }

            if (!seen.Add(n))
            {
                throw new InvalidDataException($"{TableName}: 이름 '{n}'이 두 번 나온다.");
            }

            if (!long.TryParse(Cell(row, value).Trim(), out _))
            {
                throw new InvalidDataException($"{TableName}: '{n}'의 값 '{Cell(row, value)}'이 정수(long)가 아니다 — 소수는 천분율 정수로 적는다.");
            }

            result.Add(new Constant(n, Cell(row, description).Trim()));
        }

        return result;
    }

    private static int ColumnIndex(ExcelGenerator.TableData table, string column, ExcelGenerator.ColumnInfo.RecordType type)
    {
        for (var i = 0; i < table.columnInfos.Count; i++)
        {
            var info = table.columnInfos[i];
            if (info.Name != column)
            {
                continue;
            }

            if (info.Type != type)
            {
                throw new InvalidDataException($"{TableName}: {column} 컬럼의 Type은 {type}이어야 한다(지금 {info.RawType}).");
            }

            return i;
        }

        throw new InvalidDataException($"{TableName}: {column} 컬럼이 없다 — 컬럼은 {NameColumn} · {ValueColumn} · {DescriptionColumn}이다.");
    }

    private static string Cell(string[] row, int index) => index < row.Length ? row[index] ?? "" : "";

    private static string Build(IReadOnlyList<Constant> constants)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 공용 상수(Constants.xlsx). 행 하나 = 속성 하나 — 서버 판정과 클라 표시가 같은 값을 읽는다.");
        sb.AppendLine("/// 값은 전부 long이고 소수는 천분율 정수다. <c>GameTable.LoadAll</c> 뒤에 읽는다.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Constants");
        sb.AppendLine("{");

        for (var i = 0; i < constants.Count; i++)
        {
            var c = constants[i];
            if (i > 0)
            {
                sb.AppendLine();
            }

            if (c.Description.Length > 0)
            {
                sb.AppendLine($"    /// <summary>{SecurityElement.Escape(c.Description.Replace("\r", " ").Replace("\n", " "))}</summary>");
            }

            sb.AppendLine($"    public static long {c.Name} => GameTable.{TableName}[\"{c.Name}\"].Value;");
        }

        sb.AppendLine("}");
        return CodeGenUtil.BuildFile("GameData", Array.Empty<string>(), sb.ToString());
    }
}
