// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>CharacterLevelTable 테이블의 한 행. CharacterLevelTable.bytes = MemoryPackSerializer.Serialize(List&lt;CharacterLevelTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class CharacterLevelTableRow
    {
        public int    CharacterLevelTID { get; set; }        // int [1..-]
        public int    RequiredExp       { get; set; }        // int [0..-]
        public int    AptitudePoint     { get; set; }        // int [0..-]
        public string Description       { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
