// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>CommonRewardOverrideTable 테이블의 한 행. CommonRewardOverrideTable.bytes = MemoryPackSerializer.Serialize(List&lt;CommonRewardOverrideTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class CommonRewardOverrideTableRow
    {
        public int          CommonRewardOverrideTID { get; set; }        // int [1..-]
        public IndustryType IndustryType            { get; set; }        // eIndustryType
        public int          IndustryLevel           { get; set; }        // int [1..5]
        public int          ItemTID                 { get; set; }        // int
        public int          Count                   { get; set; }        // int [1..-]
        public int          ChancePerMillion        { get; set; }        // int [1..1000000]
        public string       Description             { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
