// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>EnchantItemTable 테이블의 한 행. EnchantItemTable.bytes = MemoryPackSerializer.Serialize(List&lt;EnchantItemTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class EnchantItemTableRow
    {
        public int           ItemTID         { get; set; }        // int [1..-]
        public EnchantAction Action          { get; set; }        // eEnchantAction
        public int           SuccessPermille { get; set; }        // int [1..1000]
        public string        Description     { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
