// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>UserTraitTable 테이블의 한 행. UserTraitTable.bytes = MemoryPackSerializer.Serialize(List&lt;UserTraitTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class UserTraitTableRow
    {
        public int             UserTraitTID { get; set; }        // int [1..-]
        public string          Name         { get; set; } = "";  // string
        public int             TraitPoint   { get; set; }        // int [1..-]
        public UserTraitEffect EffectType   { get; set; }        // eUserTraitEffect
        public IndustryType    Industry     { get; set; }        // eIndustryType
        public int             EffectValue  { get; set; }        // int [0..-]
        public string          Description  { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
