// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

namespace GameData
{
    /// <summary>테이블명 → 패커 델리게이트. GenerateData가 시트명으로 조회해 .bytes를 만든다.</summary>
    public static class TableRegistry
    {
        /// <summary>Pack: 셀 행들 → 바이너리 / Verify: 라운드트립 검증(행 수 반환) / Preview: 첫 행 / Dump: 전체 행 JSON(리뷰용)</summary>
        public sealed record Entry(
            Func<IReadOnlyList<string[]>, byte[]> Pack,
            Func<byte[], int>                     Verify,
            Func<byte[], string>                  Preview,
            Func<byte[], string>                  Dump);

        public static readonly IReadOnlyDictionary<string, Entry> Tables = new Dictionary<string, Entry>
        {
            ["CharacterTable"] = new(CharacterTablePacker.Pack, CharacterTablePacker.Verify, CharacterTablePacker.Preview, CharacterTablePacker.Dump),
            ["WorkSpeedTable"] = new(WorkSpeedTablePacker.Pack, WorkSpeedTablePacker.Verify, WorkSpeedTablePacker.Preview, WorkSpeedTablePacker.Dump),
            ["CharacterLevelTable"] = new(CharacterLevelTablePacker.Pack, CharacterLevelTablePacker.Verify, CharacterLevelTablePacker.Preview, CharacterLevelTablePacker.Dump),
            ["CommonRewardTable"] = new(CommonRewardTablePacker.Pack, CommonRewardTablePacker.Verify, CommonRewardTablePacker.Preview, CommonRewardTablePacker.Dump),
            ["FarmingBasicTable"] = new(FarmingBasicTablePacker.Pack, FarmingBasicTablePacker.Verify, FarmingBasicTablePacker.Preview, FarmingBasicTablePacker.Dump),
            ["FishingBasicTable"] = new(FishingBasicTablePacker.Pack, FishingBasicTablePacker.Verify, FishingBasicTablePacker.Preview, FishingBasicTablePacker.Dump),
            ["HuntingBasicTable"] = new(HuntingBasicTablePacker.Pack, HuntingBasicTablePacker.Verify, HuntingBasicTablePacker.Preview, HuntingBasicTablePacker.Dump),
            ["LoggingBasicTable"] = new(LoggingBasicTablePacker.Pack, LoggingBasicTablePacker.Verify, LoggingBasicTablePacker.Preview, LoggingBasicTablePacker.Dump),
            ["MiningBasicTable"] = new(MiningBasicTablePacker.Pack, MiningBasicTablePacker.Verify, MiningBasicTablePacker.Preview, MiningBasicTablePacker.Dump),
            ["EquipTable"] = new(EquipTablePacker.Pack, EquipTablePacker.Verify, EquipTablePacker.Preview, EquipTablePacker.Dump),
            ["GachaItemTable"] = new(GachaItemTablePacker.Pack, GachaItemTablePacker.Verify, GachaItemTablePacker.Preview, GachaItemTablePacker.Dump),
            ["GachaInfoTable"] = new(GachaInfoTablePacker.Pack, GachaInfoTablePacker.Verify, GachaInfoTablePacker.Preview, GachaInfoTablePacker.Dump),
            ["GachaCharacterTable"] = new(GachaCharacterTablePacker.Pack, GachaCharacterTablePacker.Verify, GachaCharacterTablePacker.Preview, GachaCharacterTablePacker.Dump),
            ["GachaEquipTable"] = new(GachaEquipTablePacker.Pack, GachaEquipTablePacker.Verify, GachaEquipTablePacker.Preview, GachaEquipTablePacker.Dump),
            ["GachaGoldTable"] = new(GachaGoldTablePacker.Pack, GachaGoldTablePacker.Verify, GachaGoldTablePacker.Preview, GachaGoldTablePacker.Dump),
            ["IndustryLevelTable"] = new(IndustryLevelTablePacker.Pack, IndustryLevelTablePacker.Verify, IndustryLevelTablePacker.Preview, IndustryLevelTablePacker.Dump),
            ["ItemTable"] = new(ItemTablePacker.Pack, ItemTablePacker.Verify, ItemTablePacker.Preview, ItemTablePacker.Dump),
            ["UnlockTable"] = new(UnlockTablePacker.Pack, UnlockTablePacker.Verify, UnlockTablePacker.Preview, UnlockTablePacker.Dump),
            ["AccountLevelTable"] = new(AccountLevelTablePacker.Pack, AccountLevelTablePacker.Verify, AccountLevelTablePacker.Preview, AccountLevelTablePacker.Dump),
            ["UserTraitTable"] = new(UserTraitTablePacker.Pack, UserTraitTablePacker.Verify, UserTraitTablePacker.Preview, UserTraitTablePacker.Dump),
            ["WorkSlotTable"] = new(WorkSlotTablePacker.Pack, WorkSlotTablePacker.Verify, WorkSlotTablePacker.Preview, WorkSlotTablePacker.Dump),
        };
    }
}
