// <auto-generated>
// 이 파일은 ExcelGenerator가 Constants.xlsx(ConstantsTable)의 행으로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

namespace GameData
{
    /// <summary>
    /// 공용 상수(Constants.xlsx). 행 하나 = 속성 하나 — 서버 판정과 클라 표시가 같은 값을 읽는다.
    /// 값은 전부 long이고 소수는 천분율 정수다. <c>GameTable.LoadAll</c> 뒤에 읽는다.
    /// </summary>
    public static class Constants
    {
        /// <summary>창고 탭마다 칸 수(자원·캐릭터·장비 각각)</summary>
        public static long StorageCapacity => GameTable.ConstantsTable["StorageCapacity"].Value;

        /// <summary>안 받은 우편 상한 — 넘침 보관이 멈추는 선</summary>
        public static long MailboxCapacity => GameTable.ConstantsTable["MailboxCapacity"].Value;

        /// <summary>상자를 한 번에 여는 수</summary>
        public static long BoxOpenMax => GameTable.ConstantsTable["BoxOpenMax"].Value;

        /// <summary>뽑기 단차 횟수</summary>
        public static long GachaDrawSingle => GameTable.ConstantsTable["GachaDrawSingle"].Value;

        /// <summary>뽑기 연차 횟수</summary>
        public static long GachaDrawMulti => GameTable.ConstantsTable["GachaDrawMulti"].Value;

        /// <summary>즉시 판매가 = BasePrice × 이 값(천분율) — 거래소 하한과 묶인다</summary>
        public static long SellRatePermille => GameTable.ConstantsTable["SellRatePermille"].Value;

        /// <summary>거래소·경매장 등록 기간(시간)</summary>
        public static long AuctionListingHours => GameTable.ConstantsTable["AuctionListingHours"].Value;

        /// <summary>1인 판매 중 매물 상한</summary>
        public static long AuctionMaxActiveListings => GameTable.ConstantsTable["AuctionMaxActiveListings"].Value;

        /// <summary>단가 상한 = 하한(BasePrice) × 이 값</summary>
        public static long AuctionPriceBandMultiplier => GameTable.ConstantsTable["AuctionPriceBandMultiplier"].Value;

        /// <summary>등록비 = 총액 × 이 값(천분율, 최소 1) — 만료면 환급</summary>
        public static long AuctionListingFeePermille => GameTable.ConstantsTable["AuctionListingFeePermille"].Value;

        /// <summary>판매 수수료 = 판매액 × 이 값(천분율)</summary>
        public static long AuctionSaleFeePermille => GameTable.ConstantsTable["AuctionSaleFeePermille"].Value;

        /// <summary>거래소·경매장 조회 순간 허용 횟수</summary>
        public static long AuctionSearchBurst => GameTable.ConstantsTable["AuctionSearchBurst"].Value;

        /// <summary>조회 1회가 회복되는 간격(초)</summary>
        public static long AuctionSearchRefillSeconds => GameTable.ConstantsTable["AuctionSearchRefillSeconds"].Value;

        /// <summary>치트 — 한 번에 지급하는 캐릭터 장수 상한</summary>
        public static long CheatMaxCharacterCount => GameTable.ConstantsTable["CheatMaxCharacterCount"].Value;

        /// <summary>치트 — 정산을 한 번에 앞당기는 판정 횟수 상한</summary>
        public static long CheatMaxSettleJudges => GameTable.ConstantsTable["CheatMaxSettleJudges"].Value;

        /// <summary>게임 시작 시 열린 산업 레벨</summary>
        public static long DefaultIndustryLevel => GameTable.ConstantsTable["DefaultIndustryLevel"].Value;

        /// <summary>인챈트 부여 시 옵션 줄 수</summary>
        public static long EnchantBaseLineCount => GameTable.ConstantsTable["EnchantBaseLineCount"].Value;

        /// <summary>인챈트 줄 확장 상한 — 넘기면 EnchantLineMax</summary>
        public static long EnchantMaxLineCount => GameTable.ConstantsTable["EnchantMaxLineCount"].Value;

        /// <summary>거래소 한 번 구매 수량 상한</summary>
        public static long MarketMaxBuyCount => GameTable.ConstantsTable["MarketMaxBuyCount"].Value;

        /// <summary>거래소 가격대 줄 수</summary>
        public static long MarketPriceLevels => GameTable.ConstantsTable["MarketPriceLevels"].Value;

        /// <summary>신규 유저 시작 캐릭터 — 전 산업 적성 1 이상이어야 한다</summary>
        public static long DefaultCharacterTid => GameTable.ConstantsTable["DefaultCharacterTid"].Value;

        /// <summary>작업속도 1.0배 = 이 값(천분율 단위) — 바꾸면 ‰ 데이터 전부 재해석</summary>
        public static long WorkSpeedScale => GameTable.ConstantsTable["WorkSpeedScale"].Value;

        /// <summary>1.0배 속도의 판정 1회 시간(초)</summary>
        public static long BaseCycleSeconds => GameTable.ConstantsTable["BaseCycleSeconds"].Value;
    }
}
