// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using System;
using System.Collections.Generic;
using MemoryPack;

namespace GameData;

/// <summary>모든 데이터 테이블의 로드/조회 진입점. LoadAll에 파일 읽기 델리게이트를 주입한다(서버=File, Unity=StreamingAssets).</summary>
public static class GameTable
{
    public static TableSet<int, ItemTableRow> ItemTable { get; private set; } = null!;

    /// <summary>read: "테이블명.bytes" → 바이트. 모든 테이블을 로드/인덱싱한다.</summary>
    public static void LoadAll(Func<string, byte[]> read)
    {
        ItemTable = TableSet<int, ItemTableRow>.From(read("ItemTable.bytes"), r => r.SkillTID);
    }
}
