// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>ConstantsTable 테이블의 한 행. ConstantsTable.bytes = MemoryPackSerializer.Serialize(List&lt;ConstantsTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class ConstantsTableRow
    {
        public string Name        { get; set; } = "";  // string
        public long   Value       { get; set; }        // long
        public string Description { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
