// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>EnchantOptionTable 테이블의 한 행. EnchantOptionTable.bytes = MemoryPackSerializer.Serialize(List&lt;EnchantOptionTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class EnchantOptionTableRow
    {
        public int               OptionTID   { get; set; }        // int [1..-]
        public GlobalRarity      Grade       { get; set; }        // eGlobalRarity
        public EnchantOptionType OptionType  { get; set; }        // eEnchantOptionType
        public IndustryType      Industry    { get; set; }        // eIndustryType
        public int               Value       { get; set; }        // int [1..-]
        public int               Weight      { get; set; }        // int [1..-]
        public string            Description { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
