// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>EquipTable 테이블의 한 행. EquipTable.bytes = MemoryPackSerializer.Serialize(List&lt;EquipTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class EquipTableRow
    {
        public int          EquipTID         { get; set; }        // int [1..-]
        public string       Name             { get; set; } = "";  // string
        public GlobalRarity GlobalRarity     { get; set; }        // eGlobalRarity
        public EquipKind    EquipKind        { get; set; }        // eEquipKind
        public IndustryType Industry         { get; set; }        // eIndustryType
        public int          SpeedAddPermille { get; set; }        // int [-999..-]
        public int          BasePrice        { get; set; }        // int [0..-]
        public string       Description      { get; set; } = "";  // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
