// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData;

/// <summary>ItemTable 테이블의 한 행. ItemTable.bytes = MemoryPackSerializer.Serialize(List&lt;ItemTableRow&gt;)</summary>
[MemoryPackable]
public partial class ItemTableRow
{
    public int        SkillTID   { get; set; }        // int
    public string     Name       { get; set; } = "";  // string
    public ItemType   ItemType   { get; set; }        // eItemType
    public ItemRarity ItemRarity { get; set; }        // eItemRarity
    public int        MaxStack   { get; set; }        // int
    public string     Desciption { get; set; } = "";  // string
}
