// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>MailTemplateTable 테이블의 한 행. MailTemplateTable.bytes = MemoryPackSerializer.Serialize(List&lt;MailTemplateTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class MailTemplateTableRow
    {
        public int    MailTemplateTID { get; set; }                               // int [1..-]
        public string Title           { get; set; } = "";                         // string
        public string Body            { get; set; } = "";                         // string
        public string Sender          { get; set; } = "";                         // string
        public int    PeriodDays      { get; set; }                               // int [0..-]
        public long   Gold            { get; set; }                               // long [0..-]
        public long   Dia             { get; set; }                               // long [0..-]
        public int[]  ItemTIDs        { get; set; } = System.Array.Empty<int>();  // int[] 기본=""
        public int[]  ItemCounts      { get; set; } = System.Array.Empty<int>();  // int[] 기본=""
        public int[]  CharacterTIDs   { get; set; } = System.Array.Empty<int>();  // int[] 기본=""
        public int[]  EquipTIDs       { get; set; } = System.Array.Empty<int>();  // int[] 기본=""
        public string Description     { get; set; } = "";                         // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
