// <auto-generated>
// 이 파일은 ExcelGenerator가 Excel 데이터 시트로부터 생성했습니다. 직접 수정 금지.
// </auto-generated>

using MemoryPack;

namespace GameData
{
    /// <summary>UnlockTable 테이블의 한 행. UnlockTable.bytes = MemoryPackSerializer.Serialize(List&lt;UnlockTableRow&gt;)</summary>
    [MemoryPackable]
    public partial class UnlockTableRow
    {
        public int    UnlockTID          { get; set; }                               // int [1..-]
        public string Name               { get; set; } = "";                         // string
        public int    Gold               { get; set; }                               // int [0..-]
        public int    AccountLevel       { get; set; }                               // int [0..-]
        public int[]  RequiredUnlockTIDs { get; set; } = System.Array.Empty<int>();  // int[] 기본=""
        public string Description        { get; set; } = "";                         // string 기본="" [기획 메모 — 로직에서 읽지 않는다]
    }
}
